# simd_agent/solvers/families/_multi_region_bcs.py
"""Per-region ``0/<region>/<field>`` renderers for multi-region (CHT) cases.

Why this module exists separately from :mod:`_multi_region`:

  * The 0-field renderers are the ONLY MultiRegionBase responsibility
    that needs to inspect ``config["boundary_conditions"]`` — every other
    deterministic file (thermo, regionProperties, fvSchemes, fvSolution,
    changeDictionaryDict, …) is a function of region topology + presets.
    Putting per-patch BC logic next to topology logic mixes two
    abstraction levels and bloats the base class.
  * Free functions, no ``self`` magic — same style as :mod:`bc_fixers`
    and :mod:`legacy_fixers`.  Each function takes a ``RegionSpec`` plus
    the full ``validated_config`` and returns a complete FOAM dict text.
  * One file per logical concern: patch ownership / role inference /
    block formatting / per-field BC picking / per-field file builders.

Patch model
-----------

After ``splitMeshRegions -cellZones -overwrite``, each region's polyMesh
contains:

  * The mesh patches whose name starts with ``<region>_`` (the user's
    original patches that landed in this region's cellZone).
  * Constraint patches without a region prefix (typically ``front`` /
    ``back`` in 2D cases) — these survive into every region.
  * Auto-generated coupled patches named ``<region>_to_<other>`` (one
    per interface this region shares with a neighbour).

The renderers iterate that union and emit one BC block per patch.  The
universal :func:`bc_fixers.fix_constraint_patch_bcs` runs afterwards in
``validate_full`` and rewrites any block whose mesh-side patch type is
``symmetry`` / ``empty`` / ``wedge`` — we don't try to enforce that here.

BC source authority
-------------------

For each (patch, field) pair we look up, in order:

  1. ``config["boundary_conditions"][patch_name][field]`` — the
     precheck/UI-authored BC spec (``{type, value, …}``).
  2. The patch role inferred from ``patchClass`` / mesh type / name
     suffix (see :func:`patch_role`), mapped to a field-appropriate
     default (``inletOutlet`` for outlets, ``noSlip`` for walls, …).

If neither path produces a value, the field's ``RegionSpec`` init value
is used as the last resort.
"""

from __future__ import annotations

from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from simd_agent.run.case_spec.strategies import RegionSpec


# ────────────────────────────────────────────────────────────────────────────
# Patch ownership + role inference
# ────────────────────────────────────────────────────────────────────────────


def region_patches(region_name: str, config: dict[str, Any]) -> list[str]:
    """Mesh patch names that belong to a region after ``splitMeshRegions``.

    Ownership rule: ``name.startswith(f"{region_name}_")`` — that captures
    every patch the user authored against this region (e.g.
    ``innerFluid_inlet``, ``innerFluid_outlet``, ``innerFluid_symmetry``).

    Patches whose mesh type is ``empty`` / ``wedge`` / ``symmetry`` and
    whose name has no region prefix (``front`` / ``back``) are shared
    across every region by OpenFOAM and are included in the result so
    the renderer emits an explicit block — the universal constraint-BC
    fixer in :mod:`bc_fixers` later forces the right ``type`` on them.

    Coupled interface patches (``<region>_to_<other>``) are *not* in the
    user's mesh patch list — they're auto-generated by
    ``splitMeshRegions``.  Callers add them separately via
    :attr:`RegionSpec.interfaces`.
    """
    mesh_patches = (config.get("mesh") or {}).get("patches") or []
    owned: list[str] = []
    shared: list[str] = []
    prefix = f"{region_name}_"
    for p in mesh_patches:
        name = p["name"] if isinstance(p, dict) else getattr(p, "name", None)
        ptype = (
            p.get("type") if isinstance(p, dict) else getattr(p, "type", "")
        ) or "patch"
        if not name:
            continue
        if name.startswith(prefix):
            owned.append(name)
        elif ptype.lower() in ("empty", "wedge", "symmetry", "symmetryplane"):
            shared.append(name)
    return owned + shared


_SUFFIX_ROLES: tuple[tuple[str, str], ...] = (
    ("_inlet",     "inlet"),
    ("_outlet",    "outlet"),
    ("_symmetry",  "symmetry"),
    ("_top",       "wall"),
    ("_bottom",    "wall"),
    ("_left",      "wall"),
    ("_right",     "wall"),
    ("_left_end",  "wall"),
    ("_right_end", "wall"),
    ("_wall",      "wall"),
    ("_walls",     "wall"),
)


def patch_role(patch_name: str, config: dict[str, Any]) -> str:
    """Infer one patch's role (inlet / outlet / wall / symmetry / empty / wedge).

    Authority order:
      1. ``config["boundary_conditions"][name]["patchClass"]`` (or
         ``patch_class`` / ``patch_type`` aliases).
      2. mesh patch type — ``symmetry`` / ``empty`` / ``wedge`` map verbatim.
      3. name suffix heuristic (``*_inlet`` → inlet, …).
      4. ``front`` / ``back`` → empty.
      5. default → ``wall``.
    """
    spec = (config.get("boundary_conditions") or {}).get(patch_name)
    if isinstance(spec, dict):
        pc = (
            spec.get("patchClass")
            or spec.get("patch_class")
            or spec.get("patch_type")
        )
        if isinstance(pc, str) and pc:
            return pc.lower()

    mesh_patches = (config.get("mesh") or {}).get("patches") or []
    for p in mesh_patches:
        n = p["name"] if isinstance(p, dict) else getattr(p, "name", None)
        if n != patch_name:
            continue
        t = (
            p.get("type") if isinstance(p, dict) else getattr(p, "type", "")
        ) or ""
        lo = t.lower()
        if lo in ("symmetry", "symmetryplane"):
            return "symmetry"
        if lo == "empty":
            return "empty"
        if lo == "wedge":
            return "wedge"
        break

    low = patch_name.lower()
    for suffix, role in _SUFFIX_ROLES:
        if low.endswith(suffix):
            return role
    if patch_name in ("front", "back"):
        return "empty"
    return "wall"


def patch_field_spec(
    patch_name: str, field: str, config: dict[str, Any],
) -> dict[str, Any]:
    """Return the precheck/UI-authored BC spec for one (patch, field).

    Always returns a dict — empty when nothing is recorded.  Keeps the
    callers ``.get(...)``-friendly so missing entries fall back to the
    role-based default without special-casing.
    """
    spec = (config.get("boundary_conditions") or {}).get(patch_name) or {}
    if not isinstance(spec, dict):
        return {}
    fs = spec.get(field)
    return fs if isinstance(fs, dict) else {}


# ────────────────────────────────────────────────────────────────────────────
# Block formatting helpers
# ────────────────────────────────────────────────────────────────────────────


def _block(name: str, body: dict[str, str]) -> str:
    """Format one ``<name> { … }`` patch BC block."""
    lines = [f"    {name}", "    {"]
    for key, value in body.items():
        lines.append(f"        {key:<14}  {value};")
    lines.append("    }\n")
    return "\n".join(lines)


def _wrap_field_file(
    region_name: str,
    object_name: str,
    field_class: str,
    dimensions: str,
    internal_field: str,
    boundary_blocks: str,
) -> str:
    """Wrap the boundaryField body with the standard FOAM header / footer."""
    return (
        "FoamFile\n{\n"
        "    version     2.0;\n"
        "    format      ascii;\n"
        f"    class       {field_class};\n"
        f"    location    \"0/{region_name}\";\n"
        f"    object      {object_name};\n"
        "}\n"
        "// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //\n\n"
        f"dimensions      {dimensions};\n"
        f"internalField   uniform {internal_field};\n\n"
        "boundaryField\n{\n"
        f"{boundary_blocks}"
        "}\n\n"
        "// ************************************************************************* //\n"
    )


def _u_to_str(u: tuple[float, float, float] | list[float]) -> str:
    return f"({u[0]:g} {u[1]:g} {u[2]:g})"


# ────────────────────────────────────────────────────────────────────────────
# Per-field BC pickers — each maps (role, RegionSpec, spec) → body dict
# ────────────────────────────────────────────────────────────────────────────


# ── Constraint roles ─────────────────────────────────────────────────────
# OpenFOAM REQUIRES patchField type to match polyMesh patch type for
# constraint patches.  ``type symmetry;`` on a symmetry patch is the only
# legal block — any other type triggers "inconsistent patch and patchField
# types" and aborts the solver at startup.
#
# patch_role() returns one of these strings when the patch name suffix
# (``_symmetry`` / ``_top``/_bottom/_front/_back) or the mesh-side type
# matches a constraint.  Every per-field BC picker below MUST short-circuit
# to a bare ``{"type": <constraint>}`` when this fires — no ``value``, no
# ``inletValue``, no other entries.

_CONSTRAINT_ROLE_TO_TYPE: dict[str, str] = {
    "symmetry":      "symmetry",
    "symmetryplane": "symmetryPlane",
    "empty":         "empty",
    "wedge":         "wedge",
}


def _constraint_bc(role: str) -> dict[str, str] | None:
    """Return ``{"type": <constraint>}`` if ``role`` is a constraint role.

    Constraint patchField types take no other entries — caller short-circuits
    field-specific logic when this returns a dict.  Returns ``None`` for
    regular roles (inlet/outlet/wall) so the caller's normal logic runs.
    """
    t = _CONSTRAINT_ROLE_TO_TYPE.get(role)
    return {"type": t} if t else None


def _u_bc(role: str, region: "RegionSpec", spec: dict[str, Any]) -> dict[str, str]:
    """Velocity BC body for one patch.

    Inlet uses the user-supplied vector when ``spec.value`` is a 3-list,
    otherwise the region's ``U_init``.  Outlets release flow with
    ``inletOutlet``; walls (and coupled CHT interfaces) are ``noSlip``.
    Constraint patches (symmetry / empty / wedge) short-circuit to the
    matching constraint patchField type — required by OpenFOAM, no other
    entries allowed.
    """
    if (c := _constraint_bc(role)) is not None:
        return c
    if role == "inlet":
        val = spec.get("value")
        if isinstance(val, (list, tuple)) and len(val) == 3:
            u = (float(val[0]), float(val[1]), float(val[2]))
        elif isinstance(val, (int, float)):
            # Scalar velocity given (treat as magnitude in +x)
            u = (float(val), 0.0, 0.0)
        else:
            u = region.U_init
        return {"type": "fixedValue", "value": f"uniform {_u_to_str(u)}"}
    if role == "outlet":
        return {
            "type": "inletOutlet",
            "inletValue": "uniform (0 0 0)",
            "value": "uniform (0 0 0)",
        }
    # wall / symmetry / empty / wedge / default → noSlip (constraint patches
    # are rewritten by the universal BC fixer post-pass).
    return {"type": "noSlip"}


def _p_bc(role: str, region: "RegionSpec", spec: dict[str, Any]) -> dict[str, str]:
    """Static pressure ``p`` BC body — used by the ``calculated`` field for the
    chtMultiRegion solver pair; ``p_rgh`` is the actually-solved field."""
    if (c := _constraint_bc(role)) is not None:
        return c
    if role == "outlet":
        val = spec.get("value")
        p = float(val) if isinstance(val, (int, float)) else region.p_init
        return {"type": "fixedValue", "value": f"uniform {p:g}"}
    return {"type": "calculated", "value": f"uniform {region.p_init:g}"}


def _p_rgh_bc(role: str, region: "RegionSpec", spec: dict[str, Any]) -> dict[str, str]:
    """Modified pressure ``p_rgh`` BC body — solved field for buoyant CHT."""
    if (c := _constraint_bc(role)) is not None:
        return c
    if role == "outlet":
        val = spec.get("value")
        p = float(val) if isinstance(val, (int, float)) else region.p_init
        return {"type": "fixedValue", "value": f"uniform {p:g}"}
    return {"type": "fixedFluxPressure", "value": f"uniform {region.p_init:g}"}


def _T_bc_fluid(role: str, region: "RegionSpec", spec: dict[str, Any]) -> dict[str, str]:
    """Temperature BC body for a fluid region.  Coupled CHT interfaces use a
    dedicated block (see :func:`_coupled_T_block`); this picker handles the
    inlet / outlet / wall cases."""
    if (c := _constraint_bc(role)) is not None:
        return c
    if role == "inlet":
        val = spec.get("value")
        t = float(val) if isinstance(val, (int, float)) else region.T_init
        return {"type": "fixedValue", "value": f"uniform {t:g}"}
    if role == "outlet":
        return {
            "type": "inletOutlet",
            "inletValue": f"uniform {region.T_init:g}",
            "value": f"uniform {region.T_init:g}",
        }
    if role == "wall":
        val = spec.get("value")
        if isinstance(val, (int, float)):
            return {"type": "fixedValue", "value": f"uniform {float(val):g}"}
    return {"type": "zeroGradient"}


def _T_bc_solid(role: str, region: "RegionSpec", spec: dict[str, Any]) -> dict[str, str]:
    """Temperature BC body for a solid region — solids have no inlet/outlet so
    every non-coupled patch defaults to adiabatic (``zeroGradient``) unless the
    user explicitly fixed the temperature."""
    if (c := _constraint_bc(role)) is not None:
        return c
    val = spec.get("value")
    if isinstance(val, (int, float)):
        return {"type": "fixedValue", "value": f"uniform {float(val):g}"}
    return {"type": "zeroGradient"}


def _k_bc(role: str, region: "RegionSpec", spec: dict[str, Any]) -> dict[str, str]:
    """Turbulent kinetic energy BC body."""
    if (c := _constraint_bc(role)) is not None:
        return c
    val = spec.get("value")
    k = float(val) if isinstance(val, (int, float)) else region.k_init
    if role == "inlet":
        return {"type": "fixedValue", "value": f"uniform {k:g}"}
    if role == "outlet":
        return {
            "type": "inletOutlet",
            "inletValue": f"uniform {k:g}",
            "value": f"uniform {k:g}",
        }
    return {"type": "kqRWallFunction", "value": f"uniform {k:g}"}


def _epsilon_bc(role: str, region: "RegionSpec", spec: dict[str, Any]) -> dict[str, str]:
    if (c := _constraint_bc(role)) is not None:
        return c
    val = spec.get("value")
    e = float(val) if isinstance(val, (int, float)) else region.epsilon_init
    if role == "inlet":
        return {"type": "fixedValue", "value": f"uniform {e:g}"}
    if role == "outlet":
        return {
            "type": "inletOutlet",
            "inletValue": f"uniform {e:g}",
            "value": f"uniform {e:g}",
        }
    return {"type": "epsilonWallFunction", "value": f"uniform {e:g}"}


def _omega_bc(role: str, region: "RegionSpec", spec: dict[str, Any]) -> dict[str, str]:
    """Specific dissipation rate ω — wall function on walls, fixedValue at inlets.

    Pairs with k for kOmega / kOmegaSST.  Uses ``omegaWallFunction``
    (the canonical wall function for ω, same family as
    ``epsilonWallFunction`` / ``kqRWallFunction``).
    """
    if (c := _constraint_bc(role)) is not None:
        return c
    val = spec.get("value")
    w = float(val) if isinstance(val, (int, float)) else region.omega_init
    if role == "inlet":
        return {"type": "fixedValue", "value": f"uniform {w:g}"}
    if role == "outlet":
        return {
            "type": "inletOutlet",
            "inletValue": f"uniform {w:g}",
            "value": f"uniform {w:g}",
        }
    return {"type": "omegaWallFunction", "value": f"uniform {w:g}"}


def _nut_bc(role: str, region: "RegionSpec", spec: dict[str, Any]) -> dict[str, str]:
    """Turbulent viscosity — wall functions on walls; calculated elsewhere."""
    if (c := _constraint_bc(role)) is not None:
        return c
    if role == "wall":
        return {"type": "nutkWallFunction", "value": "uniform 0"}
    return {"type": "calculated", "value": "uniform 0"}


def _alphat_bc(role: str, region: "RegionSpec", spec: dict[str, Any]) -> dict[str, str]:
    """Turbulent thermal diffusivity (compressible) — wall function on walls.

    Pairs with :func:`_nut_bc` — same role-based wall-function/calculated
    split, but the compressible variants needed by the energy equation.
    The CHT base solver registers ``alphat`` on every fluid region's
    objectRegistry; without the file the case fails at startup with
    ``cannot find file 0/<fluid>/alphat``.
    """
    if (c := _constraint_bc(role)) is not None:
        return c
    if role == "wall":
        return {"type": "compressible::alphatWallFunction", "value": "uniform 0"}
    return {"type": "calculated", "value": "uniform 0"}


# ────────────────────────────────────────────────────────────────────────────
# Coupled CHT interface blocks
# ────────────────────────────────────────────────────────────────────────────


def _coupled_T_block(region: "RegionSpec", nbr: str) -> str:
    """Coupled temperature BC at a fluid-solid interface — the heart of CHT.

    OpenFOAM's ``compressible::turbulentTemperatureCoupledBaffleMixed``
    enforces both temperature continuity and Fourier heat-flux continuity
    across the interface.  Fluid sides use ``kappaMethod fluidThermo``
    so the BC reads κ from the local thermophysical model;
    solid sides use ``kappaMethod solidThermo``.
    """
    kappa = "fluidThermo" if region.kind == "fluid" else "solidThermo"
    return _block(
        f"{region.name}_to_{nbr}",
        {
            "type": "compressible::turbulentTemperatureCoupledBaffleMixed",
            "Tnbr": "T",
            "kappaMethod": kappa,
            "value": f"uniform {region.T_init:g}",
        },
    )


def _coupled_wall_block(
    region_name: str, nbr: str, body: dict[str, str],
) -> str:
    """Build a coupled-interface block for non-T fields.

    Velocity / pressure / turbulence don't cross the interface — it
    behaves like a wall from each side.  Same name convention as the
    coupled T block: ``<self>_to_<nbr>``.
    """
    return _block(f"{region_name}_to_{nbr}", body)


# ────────────────────────────────────────────────────────────────────────────
# Per-field file builders — the public API of this module
# ────────────────────────────────────────────────────────────────────────────


def build_region_0_U(region: "RegionSpec", config: dict[str, Any]) -> str:
    """``0/<region>/U`` with per-patch BCs.

    Fluid regions use the ``_u_bc`` picker (inlet → fixedValue, outlet →
    inletOutlet, walls → noSlip).  Solid regions don't solve momentum but
    ESI v2406's chtMultiRegionSimpleFoam still walks the solid mesh's
    objectRegistry for a ``U`` field at startup — emit the file with
    ``noSlip`` on every non-constraint patch (no flow in a solid; matches
    the OpenFOAM-4.x ``multiRegionHeaterRadiation`` ``0/U`` template
    distributed to its solid regions via changeDictionaryDict).
    Constraint patches still short-circuit to ``symmetry``/``empty``/``wedge``
    via :func:`_constraint_bc`.
    """
    blocks: list[str] = []
    for name in region_patches(region.name, config):
        role = patch_role(name, config)
        spec = patch_field_spec(name, "U", config)
        if region.kind == "solid":
            body = _constraint_bc(role) or {"type": "noSlip"}
        else:
            body = _u_bc(role, region, spec)
        blocks.append(_block(name, body))
    for nbr in region.interfaces or ():
        blocks.append(_coupled_wall_block(region.name, nbr, {"type": "noSlip"}))
    return _wrap_field_file(
        region.name, "U", "volVectorField", "[0 1 -1 0 0 0 0]",
        _u_to_str(region.U_init), "".join(blocks),
    )


def build_region_0_p(region: "RegionSpec", config: dict[str, Any]) -> str:
    """``0/<region>/p`` — calculated everywhere except fluid outlets.

    Solid regions: every patch (and every coupled interface) is
    ``calculated`` — pressure is a passive field in the solid, the
    solidThermo only reads it.  Fluid regions: the existing :func:`_p_bc`
    picker handles outlet/inlet/wall logic.
    """
    blocks: list[str] = []
    for name in region_patches(region.name, config):
        role = patch_role(name, config)
        spec = patch_field_spec(name, "p", config)
        if region.kind == "solid":
            body = _constraint_bc(role) or {
                "type": "calculated", "value": f"uniform {region.p_init:g}",
            }
        else:
            body = _p_bc(role, region, spec)
        blocks.append(_block(name, body))
    for nbr in region.interfaces or ():
        blocks.append(_coupled_wall_block(
            region.name, nbr,
            {"type": "calculated", "value": f"uniform {region.p_init:g}"},
        ))
    return _wrap_field_file(
        region.name, "p", "volScalarField", "[1 -1 -2 0 0 0 0]",
        f"{region.p_init:g}", "".join(blocks),
    )


def build_region_0_p_rgh(region: "RegionSpec", config: dict[str, Any]) -> str:
    """``0/<region>/p_rgh`` BC body.

    Fluid regions: ``fixedFluxPressure`` on walls (preserves momentum-flux
    consistency under buoyancy), ``fixedValue`` on outlets.  Solid regions:
    every patch is ``calculated`` — ``fixedFluxPressure`` is fluid-only
    (it needs the density gradient OpenFOAM only computes inside fluid
    meshes).  Matches the OpenFOAM-4.x ``multiRegionHeaterRadiation``
    ``0/p_rgh`` template distributed to solids.
    """
    blocks: list[str] = []
    for name in region_patches(region.name, config):
        role = patch_role(name, config)
        spec = patch_field_spec(name, "p_rgh", config)
        if region.kind == "solid":
            body = _constraint_bc(role) or {
                "type": "calculated", "value": f"uniform {region.p_init:g}",
            }
        else:
            body = _p_rgh_bc(role, region, spec)
        blocks.append(_block(name, body))
    for nbr in region.interfaces or ():
        coupled_type = (
            "calculated" if region.kind == "solid" else "fixedFluxPressure"
        )
        blocks.append(_coupled_wall_block(
            region.name, nbr,
            {"type": coupled_type, "value": f"uniform {region.p_init:g}"},
        ))
    return _wrap_field_file(
        region.name, "p_rgh", "volScalarField", "[1 -1 -2 0 0 0 0]",
        f"{region.p_init:g}", "".join(blocks),
    )


def build_region_0_T(region: "RegionSpec", config: dict[str, Any]) -> str:
    """``0/<region>/T`` with per-patch BCs + coupled CHT block at every interface.

    Routes the per-patch BC body through either the fluid- or solid-region
    picker depending on ``region.kind``.  The coupled
    ``compressible::turbulentTemperatureCoupledBaffleMixed`` block at each
    interface is the same on both sides up to ``kappaMethod``.
    """
    picker = _T_bc_fluid if region.kind == "fluid" else _T_bc_solid
    blocks: list[str] = []
    for name in region_patches(region.name, config):
        role = patch_role(name, config)
        spec = patch_field_spec(name, "T", config)
        blocks.append(_block(name, picker(role, region, spec)))
    for nbr in region.interfaces or ():
        blocks.append(_coupled_T_block(region, nbr))
    return _wrap_field_file(
        region.name, "T", "volScalarField", "[0 0 0 1 0 0 0]",
        f"{region.T_init:g}", "".join(blocks),
    )


def build_region_0_k(region: "RegionSpec", config: dict[str, Any]) -> str:
    """``0/<fluid>/k`` — wall function on walls, fixedValue at inlets."""
    blocks: list[str] = []
    for name in region_patches(region.name, config):
        role = patch_role(name, config)
        spec = patch_field_spec(name, "k", config)
        blocks.append(_block(name, _k_bc(role, region, spec)))
    for nbr in region.interfaces or ():
        blocks.append(_coupled_wall_block(
            region.name, nbr,
            {"type": "kqRWallFunction", "value": f"uniform {region.k_init:g}"},
        ))
    return _wrap_field_file(
        region.name, "k", "volScalarField", "[0 2 -2 0 0 0 0]",
        f"{region.k_init:g}", "".join(blocks),
    )


def build_region_0_epsilon(region: "RegionSpec", config: dict[str, Any]) -> str:
    """``0/<fluid>/epsilon`` — epsilon wall function on walls."""
    blocks: list[str] = []
    for name in region_patches(region.name, config):
        role = patch_role(name, config)
        spec = patch_field_spec(name, "epsilon", config)
        blocks.append(_block(name, _epsilon_bc(role, region, spec)))
    for nbr in region.interfaces or ():
        blocks.append(_coupled_wall_block(
            region.name, nbr,
            {
                "type": "epsilonWallFunction",
                "value": f"uniform {region.epsilon_init:g}",
            },
        ))
    return _wrap_field_file(
        region.name, "epsilon", "volScalarField", "[0 2 -3 0 0 0 0]",
        f"{region.epsilon_init:g}", "".join(blocks),
    )


def build_region_0_omega(region: "RegionSpec", config: dict[str, Any]) -> str:
    """``0/<fluid>/omega`` — kOmega / kOmegaSST specific dissipation rate.

    Dimensions ``[0 0 -1 0 0 0 0]`` (s⁻¹).  Walls use ``omegaWallFunction``;
    interior + inlet/outlet use the role-appropriate BC from
    :func:`_omega_bc`.  CHT coupling interfaces use the wall function so
    the boundary layer behaviour on the coupled wall matches what would
    happen on a plain external wall.
    """
    blocks: list[str] = []
    for name in region_patches(region.name, config):
        role = patch_role(name, config)
        spec = patch_field_spec(name, "omega", config)
        blocks.append(_block(name, _omega_bc(role, region, spec)))
    for nbr in region.interfaces or ():
        blocks.append(_coupled_wall_block(
            region.name, nbr,
            {
                "type": "omegaWallFunction",
                "value": f"uniform {region.omega_init:g}",
            },
        ))
    return _wrap_field_file(
        region.name, "omega", "volScalarField", "[0 0 -1 0 0 0 0]",
        f"{region.omega_init:g}", "".join(blocks),
    )


def build_region_0_nut(region: "RegionSpec", config: dict[str, Any]) -> str:
    """``0/<fluid>/nut`` — nut wall function on walls, calculated elsewhere."""
    blocks: list[str] = []
    for name in region_patches(region.name, config):
        role = patch_role(name, config)
        spec = patch_field_spec(name, "nut", config)
        blocks.append(_block(name, _nut_bc(role, region, spec)))
    for nbr in region.interfaces or ():
        blocks.append(_coupled_wall_block(
            region.name, nbr,
            {"type": "nutkWallFunction", "value": "uniform 0"},
        ))
    return _wrap_field_file(
        region.name, "nut", "volScalarField", "[0 2 -1 0 0 0 0]",
        "0", "".join(blocks),
    )


def build_region_0_alphat(region: "RegionSpec", config: dict[str, Any]) -> str:
    """``0/<fluid>/alphat`` — compressible turbulent thermal diffusivity.

    Required by chtMultiRegion* energy equations on every fluid region
    with RAS turbulence.  Walls use ``compressible::alphatWallFunction``;
    interior + inlet/outlet patches and the coupled CHT walls use
    ``calculated``/``alphatWallFunction`` as appropriate.

    Dimensions ``[1 -1 -1 0 0 0 0]`` (kg/m·s), matching ``mu`` — alphat
    is a *dynamic* thermal diffusivity, not a kinematic one.
    """
    blocks: list[str] = []
    for name in region_patches(region.name, config):
        role = patch_role(name, config)
        spec = patch_field_spec(name, "alphat", config)
        blocks.append(_block(name, _alphat_bc(role, region, spec)))
    for nbr in region.interfaces or ():
        blocks.append(_coupled_wall_block(
            region.name, nbr,
            {"type": "compressible::alphatWallFunction", "value": "uniform 0"},
        ))
    return _wrap_field_file(
        region.name, "alphat", "volScalarField", "[1 -1 -1 0 0 0 0]",
        "0", "".join(blocks),
    )
